### PR TITLE
Add uefi standard property for Register Access Restriction

### PR DESCRIPTION
**Pull request by samerhaj**
Fixed https://github.com/UEFI/DSD-Guide/issues/11

Signed-off-by: Samer El-Haj-Mahmoud <samer.el-haj-mahmoud@arm.com>

### CODE REVIEW

**Review by rgough71 — COMMENTED** [review]
Perhaps designating a value of 32 would be a wiser choice- define the maximum access width, or (like the ACPI specification defines) the AccessType available for a register (see 19.6.47, Field).

Otherwise, can we specify the permissible values for this property? Is 1 the only valid value?

**Comment by samerhaj** [comment]
We are treating this as an enum. I do have the permissible values, which is only "1" for now.

**Comment by ahs3** [comment]
I think I prefer the use of pre-defined strings, in this case.  It's not clear what the values will be long term, and an integer could be ambiguous.  I could easily interpret "Register Access Restriction" == 1 as a value or a Boolean, for example, and I'd rather it be very clear which it is.  Along with "max_width_32", something like "max_width_16" and "max_width_64" (or similar strings) could easily be defined up front if we expect to see those some day.

That being said, why are we putting such a value in a device property?  Isn't this something already defined in DT or as a Field() or part of _CRS() in ACPI?  For these global entries especially, I think we need to be really careful that there is no other way to describe the same information.

**Comment by samerhaj** [comment]
> I think I prefer the use of pre-defined strings, in this case. It's not clear what the values will be long term, and an integer could be ambiguous. I could easily interpret "Register Access Restriction" == 1 as a value or a Boolean, for example, and I'd rather it be very clear which it is. Along with "max_width_32", something like "max_width_16" and "max_width_64" (or similar strings) could easily be defined up front if we expect to see those some day.
> 

Makes sense. I will change to use a string enum


> That being said, why are we putting such a value in a device property? Isn't this something already defined in DT or as a Field() or part of _CRS() in ACPI? For these global entries especially, I think we need to be really careful that there is no other way to describe the same information.

The DSD is intending a slightly different meaning. This is not defining the maximum width of the register. This is defining a global flag (possibly due to HW errata) indicating that the device *does* have 64-bit registers, but it cannot accept 64-bit reads/writes. The access need to be done in 2 separate 32-bit reads/writes

**Review by ahs3 — APPROVED** [review]
Well done -- much clearer.  I'd like Rob's review of the changes, too, but these look good.

**Review by rgough71 — COMMENTED** [review]
This looks good, thanks!
Do we need text that states that any other value beyond this currently defined string is invalid and may not be used, until it gets added to this document?

**Review by rgough71 — APPROVED** [review]

**Comment by ahs3** [comment]
> This looks good, thanks!
> Do we need text that states that any other value beyond this currently defined string is invalid and may not be used, until it gets added to this document?

Yeah, that's a good idea.  I'll put this text near the top of the Appendix: When using values for device properties listed in this appendix, only explicitly defined values must be used.  System behavior with any other values is undefined.

**Comment by ahs3** [comment]
Merging.  Thanks!

**Pull request merged**
